spring:
  application:
    name: register
server:
  port: 1112
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: false



